# Generated by Django 5.1.7 on 2025-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pnr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pnrstatus",
            name="activate_date",
            field=models.DateTimeField(
                blank=True,
                help_text="keep empty for an immediate activation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pnrstatus",
            name="deactivate_date",
            field=models.DateTimeField(
                blank=True, help_text="keep empty for indefinite activation", null=True
            ),
        ),
        migrations.AddField(
            model_name="pnrstatus",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Inactive"), (1, "Active")],
                default=1,
                verbose_name="status",
            ),
        ),
    ]
